spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies


#aws configuration
aws.access.key = ${AWS_ACCESS_KEY}
aws.secret.key = ${AWS_SECRET_KEY}
aws.region = ap-south-1
aws.s3.bucketname = foodie-app-food

jwt.secret.key = dfnvjk##jsd43#jkfdsllr34r334jnje4jjjaaha

razorpay_key = ${RAZORPAY_KEY}
razorpay_secret = ${RAZORPAY_SECRET}



# General logging level
logging.level.root=INFO

# Spring Data MongoDB queries
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Mongo driver commands (show queries sent to DB)
logging.level.org.mongodb.driver.protocol.command=TRACE
logging.level.org.mongodb.driver.protocol.query=TRACE
logging.level.org.mongodb.driver.cluster=INFO
logging.level.org.mongodb.driver.connection=INFO
